"""fix_uuid_generation_for_primary_keys

Revision ID: 47dc0f1a3d8c
Revises: 3ee8a8a7fb30
Create Date: 2025-09-10 10:37:53.840787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dc0f1a3d8c'
down_revision = '3ee8a8a7fb30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
